# Site settings
baseURL = "https://jgasper22.github.io"
languageCode = "en-US"
title = "Way Up North Where the KittiWakes Play"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Local preview mode
relativeURLs = true
uglyURLs = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2023 Juli-Ann Gasper"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[params]

  # Metadata for search engines and social sharing
  author = "Juli-Ann Gasper"
  description = "Way Up North Where the Kittiwakes Play is a fun alphabet book for children and adults."
  # shareImage = "images/social.jpg"
  # twitterHandle = "onepagelove"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/book_cover.png"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
		
    [params.links.list1]
      heading = "Main"

      [[params.links.list1.link]]
        text = "Home"
        url = "index.html"
        new_tab = false # new tab
   [[params.links]]
    [params.links.list1]
      heading = "Purchase"

      [[params.links.list1.link]]
        text = "Purchase on alibris"
        url = "https://www.alibris.com/booksearch?mtype=B&keyword=way+up+north+where+the+kittiwakes+play&hs.x=0&hs.y=0"
        new_tab = true # new tab
	
	[[params.links]]
		[params.links.list1]
			heading = "See inside"
      [[params.links.list1.link]]
        text = "Big Words"
        url = "bigwords.html"
        new_tab = false # Default, open at same tab
      [[params.links.list1.link]]
        text = "The Arctic Fox"
        url = "fox.html"
        new_tab = false # Default, open at same tab


    #[params.links.list2]
    #  heading = "See inside"
    #  [[params.links.list1.link]]
    #    text = ""
  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
